//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Androdev.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Androdev.Localization.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel download progress?.
        /// </summary>
        internal static string CancelPackageDownloadText {
            get {
                return ResourceManager.GetString("CancelPackageDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel download..
        /// </summary>
        internal static string CancelPackageDownloadTitle {
            get {
                return ResourceManager.GetString("CancelPackageDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change install configuration! See log for more details..
        /// </summary>
        internal static string CantChangeConfigText {
            get {
                return ResourceManager.GetString("CantChangeConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change configuration..
        /// </summary>
        internal static string CantChangeConfigTitle {
            get {
                return ResourceManager.GetString("CantChangeConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help topics is under construction. Contact me on BBM pin:59D20DB9..
        /// </summary>
        internal static string HelpUnderConstructionText {
            get {
                return ResourceManager.GetString("HelpUnderConstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help not availiable..
        /// </summary>
        internal static string HelpUnderConstructionTitle {
            get {
                return ResourceManager.GetString("HelpUnderConstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find existing Androdev installation directory!.
        /// </summary>
        internal static string NoExistingInstallationText {
            get {
                return ResourceManager.GetString("NoExistingInstallationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Androdev not installed..
        /// </summary>
        internal static string NoExistingInstallationTitle {
            get {
                return ResourceManager.GetString("NoExistingInstallationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add UAC prompt to Eclipse IDE and Android SDK. This was meant only to prevent &quot;access denied&quot; by Windows UAC.
        ///This should not be checked when Androdev is installed outside system disk (commonly C:\ drive)..
        /// </summary>
        internal static string UacHelpText {
            get {
                return ResourceManager.GetString("UacHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is UAC compatibility?.
        /// </summary>
        internal static string UacHelpTitle {
            get {
                return ResourceManager.GetString("UacHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to uninstall?
        ///This action cannot be undone..
        /// </summary>
        internal static string UninstallConfirmationText {
            get {
                return ResourceManager.GetString("UninstallConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed uninstall?.
        /// </summary>
        internal static string UninstallConfirmationTitle {
            get {
                return ResourceManager.GetString("UninstallConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running uninstaller for Androdev. This installer is still in BETA.
        ///Manual uninstallation is preffered..
        /// </summary>
        internal static string UninstallerWarningText {
            get {
                return ResourceManager.GetString("UninstallerWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update? This action will REMOVE all existing packages and download a new one.
        ///This action cannot be undone..
        /// </summary>
        internal static string UpdateConfirmationText {
            get {
                return ResourceManager.GetString("UpdateConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update packages?.
        /// </summary>
        internal static string UpdateConfirmationTitle {
            get {
                return ResourceManager.GetString("UpdateConfirmationTitle", resourceCulture);
            }
        }
    }
}
